# Generated by Django 5.1.1 on 2024-10-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
    ]
