# Generated by Django 5.1.1 on 2024-10-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_inboxmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='rejected', max_length=10),
            preserve_default=False,
        ),
    ]
