# Generated by Django 5.1.1 on 2024-10-25 12:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_game_options_game_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Recommended image size: 286x200 pixels', max_length=255, null=True, verbose_name='thumbnail'),
        ),
    ]
