# Generated by Django 5.1.1 on 2024-10-25 12:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_game_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Recommended image ratio: 7:5', max_length=255, null=True, verbose_name='thumbnail'),
        ),
    ]
